package com.example.third_dz.data.local

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class CollectionDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var dao: CollectionDao
    private lateinit var filmDao: FilmDao

    @Before
    fun setup() {
        database = Room.inMemoryDatabaseBuilder(
            ApplicationProvider.getApplicationContext(),
            AppDatabase::class.java
        ).allowMainThreadQueries().build()
        dao = database.collectionDao()
        filmDao = database.filmDao()
    }

    @After
    fun teardown() {
        database.close()
    }

    private fun film(id: String) = FilmEntity(
        id = id,
        title = "T$id",
        originalTitle = "O$id",
        originalTitleRomanised = "OR$id",
        description = "D$id",
        director = "Dir$id",
        producer = "Prod$id",
        releaseDate = "2020",
        runningTime = "90",
        rtScore = "85",
        url = "url$id"
    )

    private fun collection(name: String = "C", color: String = "#FF0000") =
        CollectionEntity(name = name, colorHex = color, createdAt = 0L)

    @Test
    fun insert_returnsAutoGeneratedId() = runTest {
        val id = dao.insert(collection("A"))
        assertTrue(id > 0L)
    }

    @Test
    fun addFilm_andObserveFilmsInCollection() = runTest {
        val id = dao.insert(collection())
        filmDao.insertAll(listOf(film("f1"), film("f2"), film("f3")))
        dao.addFilm(CollectionFilmCrossRef(id, "f1"))
        dao.addFilm(CollectionFilmCrossRef(id, "f2"))

        val films = dao.observeFilmsInCollection(id).first()
        assertEquals(2, films.size)
        assertEquals(setOf("f1", "f2"), films.map { it.id }.toSet())
    }

    @Test
    fun addFilm_isIdempotent() = runTest {
        val id = dao.insert(collection())
        filmDao.insertAll(listOf(film("f1")))
        dao.addFilm(CollectionFilmCrossRef(id, "f1"))
        dao.addFilm(CollectionFilmCrossRef(id, "f1"))

        val films = dao.observeFilmsInCollection(id).first()
        assertEquals(1, films.size)
    }

    @Test
    fun removeFilm_dropsCrossRef() = runTest {
        val id = dao.insert(collection())
        filmDao.insertAll(listOf(film("f1"), film("f2")))
        dao.addFilm(CollectionFilmCrossRef(id, "f1"))
        dao.addFilm(CollectionFilmCrossRef(id, "f2"))

        dao.removeFilm(id, "f1")

        val films = dao.observeFilmsInCollection(id).first()
        assertEquals(1, films.size)
        assertEquals("f2", films[0].id)
    }

    @Test
    fun deleteCollection_cascadesCrossRefs() = runTest {
        val id = dao.insert(collection())
        filmDao.insertAll(listOf(film("f1")))
        dao.addFilm(CollectionFilmCrossRef(id, "f1"))

        dao.deleteById(id)

        val collectionsForFilm = dao.observeCollectionsForFilm("f1").first()
        assertTrue(collectionsForFilm.isEmpty())
    }

    @Test
    fun observeCollectionsForFilm_returnsAllParents() = runTest {
        val a = dao.insert(collection("A"))
        val b = dao.insert(collection("B"))
        filmDao.insertAll(listOf(film("f1")))
        dao.addFilm(CollectionFilmCrossRef(a, "f1"))
        dao.addFilm(CollectionFilmCrossRef(b, "f1"))

        val parents = dao.observeCollectionsForFilm("f1").first()
        assertEquals(2, parents.size)
    }
}
